### ISSUE TITLE
Value conversion error: mismatch between struct and object when applying

### ISSUE THREAD

**Issue by uncaffeinated** [MNThomson/terraform-provider-dominos#42]
**Describe the bug**
Terraform apply fails due to a value conversion error relating to "address_api_object" found in the resourceOrderData struct and the "api_object" variable used by the dominos_order resource.

Likely has to do with [this line](https://github.com/MNThomson/terraform-provider-dominos/blob/f9da83ef68468eae747944f1f62e6ba90f771449/internal/provider/resource_order.go#L76), but I'm not familiar with Go or how I would go about testing it myself.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run command `terraform apply` while there is a dominos_order resource in the plan. 

**Expected behaviour**
Terraform apply succeeds.

**Screenshots**
![image](https://github.com/MNThomson/terraform-provider-dominos/assets/42707421/41555ad3-d467-4cbc-9122-38294625c6cd)

**Desktop Versions:**
 - OS:                    Windows 10
 - Terraform Version:     1.5.7

**Comment by uncaffeinated** [comment]
I stand corrected, figuring out how to use Go and build the provider was easier than I thought. The terraform apply completes successfully now, and I've opened a small PR for it (#43 ) 

![image](https://github.com/MNThomson/terraform-provider-dominos/assets/42707421/3c2b5a62-d2e8-4f34-93aa-f7d90aaa7020)

**Comment by MNThomson** [comment]
Wow, this project is a blast from the past. I forgot how fun those 3AM Domino's coding frenzies were! `:)`

Unfortunately at this point, this provider would require a complete "from-the-ground" rewrite to get working. I do have the ancient PR #36 which _theoretically_ still works, but certainly wasn't implemented properly. Who knows, maybe I'll get Domino's cravings again late at night and just do it (my stomach will hate me though, classic Domino's).

Congrats on figuring out Go (isn't it such a great language?)! If you're interested, please continue on improving and getting this provider working on your fork. Keep me in the loop, this is truly a glorious meme-driven-development project that I'd love to see completed!

**Comment by technoamish** [comment]
Hey @uncaffeinated could you DM me how you formatted your address? I'm still getting a json payload error/value conversion error even with this fix and I'm wondering if how I'm formatting the address is the problem. For reference, my code is written in the following:

> data "dominos_address" "addr" {
>   street      = "123 Main Way"
>   city        = "Anytown Lake"
>   region      = "WA"
>   postal_code = "01234"
> }


Any help is appreciated!
